name: wise
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  flutter_svg: ^2.0.10
  image_picker: ^1.1.2
  provider: ^6.1.2
  firebase_storage: ^12.3.3
  photo_view: ^0.15.0
  google_mlkit_text_recognition: ^0.14.0
  intl: ^0.17.0
  permission_handler: ^10.2.0
  camera: ^0.10.0
  path_provider: ^2.0.11
  speech_to_text: ^7.0.0
  fl_chart: ^0.69.0
  flutter_launcher_icons: ^0.9.2
  firebase_app_check: ^0.3.1+4
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  flutter_local_notifications: ^17.2.4
  flutter_datetime_picker: ^1.5.1
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  dropdown_search: ^6.0.1
  google_sign_in: ^6.2.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/admin/
    - assets/images/logo/
    - assets/images/svg/
    - assets/images/addTransaction/
    - assets/images/user/
